GMAIL_USENAME: it.mll.ho@gmail.com
GMAIL_PASSWORD: TheMask1@Zorro
GOOGLE_MAPS_API_KEY: AIzaSyCWXdrydBFa32r8Opflk-4oL61Zd0Sucyc
FCM_API_KEY: AAAAEXz4c6s:APA91bGE8CJdgnJQPsxgVAxM7asjVEdShM6wpq6jme5sShi4S095MdCuKOGSYuaE3AlrVYKeNrjcrfJQtIoafXabnOKI5kZOBarGkPKlo-pZah3f_iT6rvLA49CpJvx7UOf6JSzL0Zb4
FCM_TOPIC_PREFIX: testing
TWILIO_ACCOUNT_SID: ACf47d0b64c1d8637b1dc7f4f91d33fba0
TWILIO_AUTH_TOKEN: f9bf5de0a0553275a6aa377a8b56f7ce
ANONYMOUS_APPLICATION_SID: APc068e4e88b11ef16b3fe94b9ca9fb779
PLIVO_AUTH_ID: MANMU4YWVJMZLIZDYWY
PLIVO_AUTH_TOKEN: YWU5YjQ5YjY2N2IxNzY2NzAyZDY2ZGY1MjkwMjc
EXOTEL_SID: amsoftsystems
EXOTEL_TOKEN: 31fbdf8f0a6734bd4bd1cdf1fd5e2f7f70ff3229
EXOTEL_CALLER_ID: 08039591060
OPERATOR_NUMBER: 7986547180
S3_ACCESS_KEY_ID: AKIAXAWJNTEUVGAJJD62
S3_SECRET_KEY: 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
S3_BUCKET: vaayu-dev
S3_REGION: 'ap-south-1'
SERVER_URL: http://alb-uat10-1592161168.ap-south-1.elb.amazonaws.com
SECRET_KEY_BASE: daef0f128e8c899673cbcc71b3d4854112006de625db4bab0116818c7a7dc5cae52fc531dfb5f153d1b7fb3021331de744683b0346317751115c1837cbc69672
ROLLBAR_ACCESS_TOKEN: 3558084d8cff47d0b4dfc7a6a09bceea
BASIC_AUTH_USER: "dhruv"
BASIC_AUTH_PASSWORD: "dhruv"
SOLUTIONS_INFINI_API_KEY: A4fbafbca93401e6c43f7c067b58a507e
SOLUTIONS_INFINI_SENDER: iMOOVE
ENALBE_GUARD_PROVISIONGING: "true"
GEOHASH_AUTO_CLUSTERING: "false"
AUTO_CLUSTER: "false"
REDIS_URL: "redis://localhost:6379/1"
JOB_WORKER_URL: "redis://localhost:6379/1"
ONBOARD_PASSENGER_TIME: 3.minutes
RAILS_MAX_THREADS: 10
#New changes
ENABLE_LINE_MANAGER_APPROVE: "true"
ENABLE_TRANSPORT_DESK_MANAGER_APPROVE: "false"
SITE_NAME: "Local"
NO_SHOW_APPROVAL_REQUIRED: "true"
CALCULATE_ETA: "true"
SEND_ANALYTICS_REPORT: "true"
test:
  DATABASE_NAME: moove_test
