default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: moove_db #<%= ENV['DATABASE_NAME'] %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: MOOVE_DEV #<%= ENV['DATABASE_USERNAME'] %>
  password:  NG$Pir7ySMJ9m&p9 #<%= ENV['DATABASE_PASSWORD'] %>
  host: moove-uat10.cjny84emnsh9.ap-south-1.rds.amazonaws.com  #<%= ENV['DATABASE_HOST'] %>
  port: 3306 #<%= ENV['DATABASE_PORT'] %>

development:
  <<: *default

test:
  <<: *default
  database: moove_test

production:
  <<: *default

staging:
  <<: *default


